CREATE TABLE login (
    user_id INT UNSIGNED AUTO_INCREMENT,
    email VARCHAR(50) NOT NULL,
    username VARCHAR(25),
    password VARCHAR(20) NOT NULL,
    role VARCHAR(50) DEFAULT 'user',
    auth_token VARCHAR(255),
    status BOOLEAN DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    UNIQUE KEY unique_email (email),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;